name: eng
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
 # for project Second Project This dependency
  provider: ^6.0.2
    # http for the wallpaper 
    # getX for the Wallpaper
  http: ^0.13.4
  get: ^4.6.1
  flutter_cache_manager: ^3.3.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  sqflite: ^2.0.3+1


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg