// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFWgM7js8AvLyyAjTXRz0hQJwRtogsBX8',
    appId: '1:589324556492:web:848d922b4a9b3eac1c0a69',
    messagingSenderId: '589324556492',
    projectId: 'sameerloginproj',
    authDomain: 'sameerloginproj.firebaseapp.com',
    storageBucket: 'sameerloginproj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQYFwUrYAjRihb7-K68x8vgA6_tkeJm8Y',
    appId: '1:589324556492:android:eb555743fdd3db241c0a69',
    messagingSenderId: '589324556492',
    projectId: 'sameerloginproj',
    storageBucket: 'sameerloginproj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkTcA_5yEM3G_Y1cMhyOHrW4o4ls012Kw',
    appId: '1:589324556492:ios:7295d89baeaf076c1c0a69',
    messagingSenderId: '589324556492',
    projectId: 'sameerloginproj',
    storageBucket: 'sameerloginproj.appspot.com',
    iosClientId: '589324556492-40vj0jmnautticqggj490ee7c0u0e8nt.apps.googleusercontent.com',
    iosBundleId: 'com.adilayoubbhat.flutteChallange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkTcA_5yEM3G_Y1cMhyOHrW4o4ls012Kw',
    appId: '1:589324556492:ios:09988cb869c464431c0a69',
    messagingSenderId: '589324556492',
    projectId: 'sameerloginproj',
    storageBucket: 'sameerloginproj.appspot.com',
    iosClientId: '589324556492-s053i3o1nnadlg11l0fvai96nqglfr7o.apps.googleusercontent.com',
    iosBundleId: 'com.adilayoubbhat.flutteChallange.RunnerTests',
  );
}
