// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRwiou0S__78gmqkSMZP8rqkX1laiMKT8',
    appId: '1:1016031509323:web:7d9d9605fc68625f5846ce',
    messagingSenderId: '1016031509323',
    projectId: 'derive-clone',
    authDomain: 'derive-clone.firebaseapp.com',
    storageBucket: 'derive-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBRphSCY22Nk1Xd1n3b_fBYvTaA3VVaPQ',
    appId: '1:1016031509323:android:2803b881c07a648d5846ce',
    messagingSenderId: '1016031509323',
    projectId: 'derive-clone',
    storageBucket: 'derive-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQuu00YU1uX6fT6NNlUEJ4iDrZ0gEPpy0',
    appId: '1:1016031509323:ios:4547bf91a5ce9e655846ce',
    messagingSenderId: '1016031509323',
    projectId: 'derive-clone',
    storageBucket: 'derive-clone.appspot.com',
    iosClientId: '1016031509323-mt4v3slphb9c773sl7vaumoo4imn5jg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQuu00YU1uX6fT6NNlUEJ4iDrZ0gEPpy0',
    appId: '1:1016031509323:ios:9a933aa865213dcd5846ce',
    messagingSenderId: '1016031509323',
    projectId: 'derive-clone',
    storageBucket: 'derive-clone.appspot.com',
    iosClientId: '1016031509323-3hprm0s57neieua6mkscca9gj1dll84p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchallenge.RunnerTests',
  );
}
