// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-HM19AkXewvnmyo9Q3pkethpXGeVqwBA',
    appId: '1:692335704891:web:92bf07e4c066e7eaabd51e',
    messagingSenderId: '692335704891',
    projectId: 'adilayoubchatapplication',
    authDomain: 'adilayoubchatapplication.firebaseapp.com',
    storageBucket: 'adilayoubchatapplication.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-W8XgFcNFII9oWC4q6wbHk_9svFW0uDk',
    appId: '1:692335704891:android:9a57257012c1268fabd51e',
    messagingSenderId: '692335704891',
    projectId: 'adilayoubchatapplication',
    storageBucket: 'adilayoubchatapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsr-XrERCaPoBZk2UpiyUqBzLHse_87WU',
    appId: '1:692335704891:ios:6399d15c926c0eefabd51e',
    messagingSenderId: '692335704891',
    projectId: 'adilayoubchatapplication',
    storageBucket: 'adilayoubchatapplication.appspot.com',
    iosClientId: '692335704891-i98v18go28pr3mmtvh9sib5aplbstdhb.apps.googleusercontent.com',
    iosBundleId: 'com.adilayoubbhat.flutteChallange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsr-XrERCaPoBZk2UpiyUqBzLHse_87WU',
    appId: '1:692335704891:ios:8966faf03ec74e9babd51e',
    messagingSenderId: '692335704891',
    projectId: 'adilayoubchatapplication',
    storageBucket: 'adilayoubchatapplication.appspot.com',
    iosClientId: '692335704891-9h8ph8sfuvkv286h9tj6j6pn4qkjkeke.apps.googleusercontent.com',
    iosBundleId: 'com.adilayoubbhat.flutteChallange.RunnerTests',
  );
}
